version: "3.1"

services:
  telegrambot:
    image: telegrambot
    restart: on-failure
    ports: 
      - 8000:8000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
